### ISSUE TITLE
det() and solve() take self rather than &self

### ISSUE THREAD

**Issue by yongqli** [AtheMathmo/rulinalg#129]
Currently the signature is `fn det(self) -> T`. This consumes the `Matrix` so we cannot do anything else with it. This doesn't seem necessary, it should be changed to `fn det(&self) -> T` instead.

**Comment by AtheMathmo** [comment]
This was made as part of the most recent breaking change. Basically you can retain the previous functionality by calling `mat.clone().det()`.

Previously we took a reference but then in the `lup_decomp` function, which is called within `det`, we would clone `self`. This is poor practice as we force the user to clone their data. By consuming `self` the choice is given to the user.

I'd like to provide an implementation which does not consume the matrix, but for now we decided it was best that the API was transparent.

**Comment by AtheMathmo** [comment]
Oh and I forgot to say - we will soon be updating the `lu_decomp` function so that we can have a persistent `solve` function. You can check progress in #94 .

**Comment by Andlon** [comment]
As far as I know, it's not possible to compute the determinant of a _general_ matrix without using at least O(n<sup>2</sup>) memory. The idea is then to take `self` and reuse its memory, so that the _additional_ memory costs are much less (once the LU rework in #94 is complete, only O(n) additional memory will be necessary for LU decomposition). My point is that consuming `self` here is the right choice, and I think we cannot ever provide a function which only takes `&self` while avoiding excessive memory overhead.

@AtheMathmo: I think perhaps new users coming from e.g. NumPy might be a bit confused as to why these functions consume `self`. We should probably improve the docs in that regard. Once again, this will be easier with #94 in place...

**Comment by AtheMathmo** [comment]
I'm going to close this issue now. Sorry that this was unclear @yongqli .

I agree that adding some more documentation for this _might_ be worthwhile. However, given your reassuring comments I'll hold off for now. The changelog explains a little more about this change - I'll modify this post so that this information is more readily available and hope any other confused parties find their way here. If this proves futile in the future (I'm thinking after the #94 improvements land) then I will happily update the docs!
