### ISSUE TITLE
`sum_rows` calculates sum of columns, `sum_cols` calculates sum of rows

### ISSUE THREAD

**Issue by scholtzan** [AtheMathmo/rulinalg#25]
`sum_rows` seems to return a vector equal to the sum of the matrices columns instead of the matrices rows.
Similarly, `sum_cols` calculates the sum of the matrices rows.

Here a small code example:

```rust
let m = Matrix::new(2, 3, vec![1.0, 2.0, 3.0,
                               4.0, 5.0, 6.0]);
// => Matrix { rows: 2, cols: 3, data: [1, 2, 3, 4, 5, 6] }

m.sum_cols();
// => Vector { size: 2, data: [6, 15] }
// I expected: Vector { size: 3, data: [5, 7, 9]}

m.sum_rows();
// => Vector { size: 3, data: [5, 7, 9] }
// I expected: Vector { size: 2, data: [6, 15] }
```

**Comment by AtheMathmo** [comment]
Thanks for opening this issue. I'm not sure I can give a good answer to this one - the current implementation is definitely intentional.

I'll try to explain the reasoning:

In the current implementation `sum_rows` should be read as _add all of the rows together_. So in your example the matrix has 2 rows, each containing 3 elements. Adding these together should result in a single row with 3 elements. I believe your implementation would make more sense if read as _sum along the rows_.

I know that this disagrees with numpy for example - though they do explicitly state in the documentation that the sum is _along the axis_. I think at the very least this confusion should be eliminated in the rulinalg documentation. Or perhaps we should just adopt the _along the axis_ convention.

I'll leave this issue open as I decide how best to handle this...

**Comment by AtheMathmo** [comment]
Actually it seems I wasn't remembering numpy's implementation correctly:

```python
>>> import numpy as np
>>> a = np.array([[1,2,3],[4,5,6]])
>>> a.shape
(2,3)
>>> a.sum(0) # sum the rows
array([5, 7, 9])
>>> a.sum(1) # sum the cols
array([ 6, 15])
```

It seems that we do agree currently?

**Comment by scholtzan** [comment]
Yes, currently the results match those of numpy. 
I didn't look at the numpy implementation at first so I didn't notice that the is sum calculated over the axis instead of along the axis.
Thank you for clarifying!

**Comment by AtheMathmo** [comment]
Of course!

In that case I'll close this issue and add a new one for improving the documentation a little. Thanks again for bringing this to my attention.
