### ISSUE TITLE
Wrap rows and cols into a tuple or a struct

### ISSUE THREAD

**Issue by c410-f3r** [AtheMathmo/rulinalg#63]
Would be nice to discuss the possibility of using a tuple or a struct for rows and columns in matrices constructors/structs.

For example, the following code:
```
pub struct Matrix<T> {
    rows: usize,
    cols: usize,
    data: Vec<T>,
}

fn from_fn<F>(rows: usize, cols: usize, mut f: F) -> Matrix<T>;
fn rows(&self) -> usize { self.rows }
```

Would be something like this using a tuple:
```
pub struct Matrix<T> {
    data: Vec<T>,
    shape: (usize, usize),
}

fn from_fn<F>(shape: (usize, usize), mut f: F) -> Matrix<T>;
fn rows(&self) -> usize { self.shape.0 }
```

Or something like this using a struct:
```
struct Shape {
    rows: usize,
    cols: usize,
}

pub struct Matrix<T> {
    data: Vec<T>,
    shape: Shape,
}

fn from_fn<F>(shape: Shape, mut f: F) -> Matrix<T>;
fn rows(&self) -> usize { self.shape.rows }
```

**Comment by AtheMathmo** [comment]
Thanks for writing this up.

I think that for now I prefer the current approach. The reasoning being that (at least for now and probably forever) we will only support 2-d matrices and 1-d vectors. As such it seems a reasonable trade off to add an extra field and reduce complexity.

I think that a tuple is a bad idea - as we need our user to know the positioning of each item in the tuple. The struct is more viable in my eyes but still feels like unnecessary complication.

Of course, that is just my opinion and I would be more than happy to hear from others.

**Comment by Andlon** [comment]
I think a more general approach would make sense if we were to support n-dimensional arrays (or more general tensors than just matrices). As @AtheMathmo points out though, that's not really something that he has in mind for rulinalg. Users of NumPy might be used to dealing with `shape`, but I suspect users would expect that a `Matrix` type has something akin to `rows()` and `cols()`, since they are fundamental properties of a matrix (and thus it's reasonable to have them as fields).

**Comment by AtheMathmo** [comment]
If you have no additional comments I'll close this out @c410-f3r . But thanks again for opening!

**Comment by c410-f3r** [comment]
Hey @Andlon and @AtheMathmo, thanks for answering and for being receptive. The issue can be closed :)
